name: sharek
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  bot_toast: ^4.0.3
  dio: ^5.0.3

  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^3.0.3
  get_storage: ^2.1.1
  freezed_annotation: ^2.2.0
  pretty_dio_logger: ^1.3.1
  shimmer: ^2.0.0
  cached_network_image: ^3.2.3
  image_pickers: ^2.0.1
  permission_handler: ^10.2.0
  flutter_form_builder: ^7.8.0
  responsive_framework: ^0.2.0
  flutter_localizations:
    sdk: flutter
  supercharged: ^2.1.1
  flutter_svg: ^2.0.4
  app_settings: ^4.2.0
  flutter_native_splash: ^2.2.19
  sentry_logging: ^7.2.0
  sentry_flutter: ^7.2.0
  round_spot: ^0.5.0
  leak_tracker: ^2.0.1
  iconsax: ^0.0.8
  pinput: ^2.2.31
  firebase_core: ^2.8.0

dev_dependencies:
  freezed: any
  build_runner: any
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal_Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal_Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal_Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal_Bold.ttf
          weight: 700
    - family: SuiizIcons
      fonts:
        - asset: assets/fonts/SuiizIcons.ttf

flutter_native_splash: null
flutter_icons:
  android: "launcher_icon"
  ios: true

flutter_app_name:
  name: "Sharek "
